<!-- Main.svelte -->

<script>
	// Import the ProjectCard component
	import ProjectCard from './ProjectCard.svelte';
	import ExpressPolar from '$lib/portfolio/express-polar.png';
	import NoHead from '$lib/portfolio/no-head.jpg';
	import NoMind from '$lib/portfolio/no-mind.png';
    import AlchyBox from '$lib/portfolio/alchy-box.png';

	// Define an array of project data
	let projects = [
		{
			title: 'AlchyBox',
			role: 'Solo Developer',
			date: 'Current',
            location: 'College/MGDC',
			description: "A 2-15 player party game developed using Unreal Engine 5, featuring websocket technology that enables players to use their phones as controllers. In this game, players collaborate to create humorous narratives, expanding upon stories generated by the game. A key mechanic involves taking shots; at various points in the story, players can challenge their friends to take shots in exchange for multipliers.",
			image: AlchyBox
		},
		{
			title: 'Express Polar',
			role: 'Solo Developer',
			date: 'May, 2023',
            location: 'College/MGDC',
			description: 'This project was the first place winner in the MU Design Competetion and was also desplayed in the Miami Game Design Senior Project Fair. The game was entirly programmed in C++ using Unreal Engine In this game the player speed runnes through a randomly generated train with many twists and turns as scary conductor chases you down. This game also utilizes epic online services (EOS) for an online multiplayer experience.',
			image: ExpressPolar,
		},
        {
			title: 'MGDC: No Mind',
			role: 'Programming and Design Lead',
			date: 'October, 2022',
            location: 'College/MGDC',
			description: 'As a leader in the Miami Game Design Club, I created an immersive interrogation-style game where players use persuasion tactics to uncover the truth. With engaging dialogue and high-pressure gameplay, players will feel like they\'re in the hot seat.',
			image: NoMind
		},
		{
			title: 'MGDC: No Head',
			role: 'Programming and Design Lead',
			date: 'September 22, 2022',
            location: 'College/MGDC',
			description: 'This is a project I lead at Miami Game Design Club, I created a unique gameplay experience where players navigate a zombie apocalypse without a body. We crafted a thrilling puzzle-solving game where the player needs to manager either carring around their own head or an weapon to kill robot zombies',
			image: NoHead
		},
	];
</script>

<main class="pt-16">
    <p class="text-center text-surface-400 text-sm m-10">Certain projects cannot be shown due to my commitment to uphold non-disclosure agreements (NDAs).</p>
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="grid grid-cols-1 lg:grid-cols-3 gap-20">
			<div class="grid gap-10 items-start">
				{#each projects as project, index (project.title)}
					{#if index % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
			<div class="grid gap-10 items-start">
				{#each projects as project, index (project.title)}
					{#if (index - 1) % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
			<div class="grid gap-10 items-start">
				{#each projects as project, index (project.title)}
					{#if (index - 2) % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
		</div>
	</div>
</main>
