<!-- Main.svelte -->

<script>
	// Import the ProjectCard component
	import ProjectCard from './ProjectCard.svelte';
	import ExpressPolar from '$lib/portfolio/express-polar.png';
	import NoHead from '$lib/portfolio/no-head.jpg';
	import NoMind from '$lib/portfolio/no-mind.png';
	import HotelAndMecha from '$lib/portfolio/hotelandmecha.png';
    import Bolt from '$lib/portfolio/bolt.png';
    import Cooptapus from '$lib/portfolio/COPano.png';
    import HideAndSeek from '$lib/portfolio/hideandseek.jpg';
    import MidnightHeist from '$lib/portfolio/midheist.png';
    import PetCity from '$lib/portfolio/petcity.jpg';
    import Pizza from '$lib/portfolio/pizza.jpg';
    import PuttPutt from '$lib/portfolio/puttputt.jpg';
    import SlapStick from '$lib/portfolio/slapstick.png';
    import Tycoon from '$lib/portfolio/tycoon.jpg';
    import Windup from '$lib/portfolio/windup.png';
    import AlchyBox from '$lib/portfolio/alchy-box.png';
    import ShortFuse from '$lib/portfolio/shortfuse.jpg';
    

	// Define an array of project data
	let projects = [
		{
			title: 'AlchyBox',
			role: 'Solo Developer',
			date: 'Current',
			location: 'College/MGDC',
            href: "/portfolio/feature-1",
			description:
				'A 2-15 player party game developed using Unreal Engine 5, featuring websocket technology that enables players to use their phones as controllers. In this game, players collaborate to create humorous narratives, expanding upon stories generated by the game. A key mechanic involves taking shots; at various points in the story, players can challenge their friends to take shots in exchange for multipliers.',
			image: AlchyBox
		},
		{
			title: 'Express Polar',
			role: 'Solo Developer',
			date: 'May, 2023',
			location: 'College/MGDC',
            href: "/portfolio/feature-2",
			description:
				'This project was the first place winner in the MU Design Competition and was also displayed in the Miami Game Design Senior Project Fair. The game was entirely programmed in C++ using Unreal Engine. In this game, the player speed runs through a randomly generated train with many twists and turns as a scary conductor chases you down. This game also utilizes Epic Online Services (EOS) for an online multiplayer experience.',
			image: ExpressPolar
		},
		{
			title: 'No Mind',
			role: 'Programming and Design Lead',
			date: 'October 28, 2022',
			location: 'College/MGDC',
			description:
				"As a leader in the Miami Game Design Club, I created an immersive interrogation-style game where players use persuasion tactics to uncover the truth. With engaging dialogue and high-pressure gameplay, players will feel like they're in the hot seat.",
			image: NoMind
		},
		{
			title: 'No Head',
			role: 'Programming and Design Lead',
			date: 'September 22, 2022',
			location: 'College/MGDC',
			description:
				'This is a project I led at Miami Game Design Club. I created a unique gameplay experience where players navigate a zombie apocalypse without a body. We crafted a thrilling puzzle-solving game where the player needs to manage either carrying around their own head or a weapon to kill robot zombies.',
			image: NoHead
		},
		{
			title: 'Hotel Outage & Mechaball',
			role: 'Programming and Design Lead',
			date: 'February 2022',
			location: 'College/MGDC',
			description:
				'Hotel Outage challenges players to keep guests satisfied while navigating a haunted hotel with dangerous ghosts, while Mechaball puts players in the cockpit of a mech for a futuristic game of soccer, designed specifically for virtual reality in Unreal Engine 5.',
			image: HotelAndMecha
		},
		{
			title: 'SlapStick',
			role: '3D Modeling and Design Co-Lead',
			date: 'Global Game Jam, "Duality", June 21, 2022',
			location: 'College/MGDC',
			description:
				'In this fast-paced and hilarious game, players use their left hand to slap opponents and their right hand to fling a sticky hand and grapple onto objects or even the enemies.',
			image: SlapStick
		},
		{
			title: 'Wind-Up',
			role: '3D Modeling and Design Co-Lead',
			date: 'Area of Effect Game Jam, "Signs of Life", September 26, 2021',
			location: 'College/MGDC',
			description:
				'In this charming puzzle game, you play as a wind-up mouse with a magical ability to bring other toys to life just by touching them. Guide the mouse through various levels as you bring the other toys to life and use their unique abilities to solve puzzles and progress through the game. This project was placed on the podium with the creativity award.',
			image: Windup
		},
		{
			title: 'Cooptapus',
			role: 'Programming and Design Lead',
			date: '2023',
			location: 'College/MGDC',
			description:
				'Immerse yourself in an oceanic adventure with Cooptapus, the exciting new game where you and your friends play as a giant squid on a mission to destroy ships. Enjoy the thrill of casual party play while unleashing your inner sea monster in my solo developed Steam release.',
			image: Cooptapus
		},
		{
			title: 'Putt-Putt City',
			role: 'Programming and Design Lead',
			date: 'May 19, 2020',
			location: 'Nitric Concepts - Microsoft Partnership Program',
			description:
				'Play with over 27 courses while you travel the world and uncover new secrets! What will you find in this unforgettable adventure through time and space? Welcome to your Putt-Putt City.',
			image: PuttPutt
		},
		{
			title: 'Pizza Parlor',
			role: 'Designer and 3D Modeling',
			date: 'August 20, 2019',
			location: 'Nitric Concepts - Microsoft Partnership Program',
			description:
				'A new pizza shop has opened up in town! Role-play as a pizza chef or as a pizza. Craft furniture and decorate your house or explore and make your own adventure!',
			image: Pizza
		},
		{
			title: 'Business Tycoon',
			role: 'Programming and 3D Modeling',
			date: 'August 13, 2019',
			location: 'Nitric Concepts - Microsoft Partnership Program',
			description:
				'Own every building and become the best person in the city of Mineland. The future is in reach with Business Tycoon!',
			image: Tycoon
		},
		{
			title: 'Hide and Seek: Resort!',
			role: 'Programming and 3D Modeling',
			date: 'August 6, 2019',
			location: 'Nitric Concepts - Microsoft Partnership Program',
			description:
				'Welcome to the Hide and Seek Resort! Play survival with the custom mobs or play a game of hide & seek with friends. Ride boats down the slippery iced mountains or discover the many sneaky hiding places in the cabin!',
			image: HideAndSeek
		},
		{
			title: 'Pet City',
			role: 'Designer and 3D Modeling',
			date: 'April 16, 2019',
			location: 'Nitric Concepts - Microsoft Partnership Program',
			description:
				"Pet City is the ideal place to raise your new pets! Take it to the park, an aquarium, or just around town! Live your pet's dream in Pet City!",
			image: PetCity
		},
		{
			title: 'Midnight Heist',
			role: 'Project Lead, 3D Modeling, Gameplay Design',
			date: 'Sep 26, 2020',
			location: "Minecraft Realm's Minigame",
			description:
				"Join your friends on a heist to steal treasures from the wealthy or play as a cop and hunt down the thieves. As the project's lead 3D modeler and gameplay designer, I oversaw the development of this exciting multiplayer game.",
			image: MidnightHeist
		},
		{
			title: 'Bolt',
			role: '3D Modeling, Design, Co-Project Lead',
			date: 'June 6, 2019',
			location: "Minecraft Realm's Minigame",
			description:
				'In this fast-paced bow game, players must shoot their opponents to achieve a range of objectives across various game modes and maps. I was a co-lead on this project, contributing my skills in 3D modeling and design to help bring Bolt to life.',
			image: Bolt
		},
		{
			title: 'Short Fuse',
			role: 'Design and 3D Modeling',
			date: 'Feb 23, 2018',
			location: "Minecraft Realm's Minigame",
			description:
				"This Minecraft adaptation of the classic game Bomberman features unique twists such as power-ups and reward-based progression. As a designer and 3D modeler on the project, I helped craft the game's look and feel, contributing to a fun and engaging player experience.",
			image: ShortFuse
		}
	];
</script>

<main class="pt-16">
	<p class="text-center text-surface-400 text-sm m-10">
		Certain projects cannot be shown due to my commitment to uphold non-disclosure agreements
		(NDAs).
	</p>
	<div class="container mx-auto px-4 sm:px-6 lg:px-8 mb-10">
		<div class="grid grid-cols-1 lg:grid-cols-3 gap-20">
			<div class="grid gap-10 mb-auto">
				{#each projects as project, index (project.title)}
					{#if index % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
			<div class="grid gap-10 mb-auto">
				{#each projects as project, index (project.title)}
					{#if (index - 1) % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
			<div class="grid gap-10 mb-auto">
				{#each projects as project, index (project.title)}
					{#if (index - 2) % 3 === 0}
						<ProjectCard {project} />
					{/if}
				{/each}
			</div>
		</div>
	</div>
</main>
